/*
 * Decompiled with CFR 0.152.
 */
package org.lwjgl.system.linux.liburing;

import org.lwjgl.system.Library;
import org.lwjgl.system.NativeType;
import org.lwjgl.system.linux.liburing.IOURingParams;

public class LibIOURing {
    public static final int IORING_FILE_INDEX_ALLOC;
    public static final int IORING_MAX_ENTRIES;
    public static final int IOSQE_FIXED_FILE_BIT;
    public static final int IOSQE_IO_DRAIN_BIT;
    public static final int IOSQE_IO_LINK_BIT;
    public static final int IOSQE_IO_HARDLINK_BIT;
    public static final int IOSQE_ASYNC_BIT;
    public static final int IOSQE_BUFFER_SELECT_BIT;
    public static final int IOSQE_CQE_SKIP_SUCCESS_BIT;
    public static final int IOSQE_FIXED_FILE;
    public static final int IOSQE_IO_DRAIN;
    public static final int IOSQE_IO_LINK;
    public static final int IOSQE_IO_HARDLINK;
    public static final int IOSQE_ASYNC;
    public static final int IOSQE_BUFFER_SELECT;
    public static final int IOSQE_CQE_SKIP_SUCCESS;
    public static final int IORING_SETUP_IOPOLL;
    public static final int IORING_SETUP_SQPOLL;
    public static final int IORING_SETUP_SQ_AFF;
    public static final int IORING_SETUP_CQSIZE;
    public static final int IORING_SETUP_CLAMP;
    public static final int IORING_SETUP_ATTACH_WQ;
    public static final int IORING_SETUP_R_DISABLED;
    public static final int IORING_SETUP_SUBMIT_ALL;
    public static final int IORING_SETUP_COOP_TASKRUN;
    public static final int IORING_SETUP_TASKRUN_FLAG;
    public static final int IORING_SETUP_SQE128;
    public static final int IORING_SETUP_CQE32;
    public static final int IORING_SETUP_SINGLE_ISSUER;
    public static final int IORING_SETUP_DEFER_TASKRUN;
    public static final byte IORING_OP_NOP;
    public static final byte IORING_OP_READV;
    public static final byte IORING_OP_WRITEV;
    public static final byte IORING_OP_FSYNC;
    public static final byte IORING_OP_READ_FIXED;
    public static final byte IORING_OP_WRITE_FIXED;
    public static final byte IORING_OP_POLL_ADD;
    public static final byte IORING_OP_POLL_REMOVE;
    public static final byte IORING_OP_SYNC_FILE_RANGE;
    public static final byte IORING_OP_SENDMSG;
    public static final byte IORING_OP_RECVMSG;
    public static final byte IORING_OP_TIMEOUT;
    public static final byte IORING_OP_TIMEOUT_REMOVE;
    public static final byte IORING_OP_ACCEPT;
    public static final byte IORING_OP_ASYNC_CANCEL;
    public static final byte IORING_OP_LINK_TIMEOUT;
    public static final byte IORING_OP_CONNECT;
    public static final byte IORING_OP_FALLOCATE;
    public static final byte IORING_OP_OPENAT;
    public static final byte IORING_OP_CLOSE;
    public static final byte IORING_OP_FILES_UPDATE;
    public static final byte IORING_OP_STATX;
    public static final byte IORING_OP_READ;
    public static final byte IORING_OP_WRITE;
    public static final byte IORING_OP_FADVISE;
    public static final byte IORING_OP_MADVISE;
    public static final byte IORING_OP_SEND;
    public static final byte IORING_OP_RECV;
    public static final byte IORING_OP_OPENAT2;
    public static final byte IORING_OP_EPOLL_CTL;
    public static final byte IORING_OP_SPLICE;
    public static final byte IORING_OP_PROVIDE_BUFFERS;
    public static final byte IORING_OP_REMOVE_BUFFERS;
    public static final byte IORING_OP_TEE;
    public static final byte IORING_OP_SHUTDOWN;
    public static final byte IORING_OP_RENAMEAT;
    public static final byte IORING_OP_UNLINKAT;
    public static final byte IORING_OP_MKDIRAT;
    public static final byte IORING_OP_SYMLINKAT;
    public static final byte IORING_OP_LINKAT;
    public static final byte IORING_OP_MSG_RING;
    public static final byte IORING_OP_FSETXATTR;
    public static final byte IORING_OP_SETXATTR;
    public static final byte IORING_OP_FGETXATTR;
    public static final byte IORING_OP_GETXATTR;
    public static final byte IORING_OP_SOCKET;
    public static final byte IORING_OP_URING_CMD;
    public static final byte IORING_OP_SEND_ZC;
    public static final byte IORING_OP_SENDMSG_ZC;
    public static final byte IORING_OP_LAST;
    public static final int IORING_URING_CMD_FIXED;
    public static final int IORING_FSYNC_DATASYNC;
    public static final int IORING_TIMEOUT_ABS;
    public static final int IORING_TIMEOUT_UPDATE;
    public static final int IORING_TIMEOUT_BOOTTIME;
    public static final int IORING_TIMEOUT_REALTIME;
    public static final int IORING_LINK_TIMEOUT_UPDATE;
    public static final int IORING_TIMEOUT_ETIME_SUCCESS;
    public static final int IORING_TIMEOUT_MULTISHOT;
    public static final int IORING_TIMEOUT_CLOCK_MASK;
    public static final int IORING_TIMEOUT_UPDATE_MASK;
    public static final int IORING_SPLICE_F_FD_IN_FIXED;
    public static final int IORING_POLL_ADD_MULTI;
    public static final int IORING_POLL_UPDATE_EVENTS;
    public static final int IORING_POLL_UPDATE_USER_DATA;
    public static final int IORING_POLL_ADD_LEVEL;
    public static final int IORING_ASYNC_CANCEL_ALL;
    public static final int IORING_ASYNC_CANCEL_FD;
    public static final int IORING_ASYNC_CANCEL_ANY;
    public static final int IORING_ASYNC_CANCEL_FD_FIXED;
    public static final int IORING_RECVSEND_POLL_FIRST;
    public static final int IORING_RECV_MULTISHOT;
    public static final int IORING_RECVSEND_FIXED_BUF;
    public static final int IORING_SEND_ZC_REPORT_USAGE;
    public static final int IORING_NOTIF_USAGE_ZC_COPIED;
    public static final int IORING_ACCEPT_MULTISHOT;
    public static final int IORING_MSG_DATA;
    public static final int IORING_MSG_SEND_FD;
    public static final int IORING_MSG_RING_CQE_SKIP;
    public static final int IORING_MSG_RING_FLAGS_PASS;
    public static final int IORING_CQE_F_BUFFER;
    public static final int IORING_CQE_F_MORE;
    public static final int IORING_CQE_F_SOCK_NONEMPTY;
    public static final int IORING_CQE_F_NOTIF;
    public static final int IORING_CQE_BUFFER_SHIFT;
    public static final long IORING_OFF_SQ_RING;
    public static final long IORING_OFF_CQ_RING;
    public static final long IORING_OFF_SQES;
    public static final long IORING_OFF_PBUF_RING;
    public static final long IORING_OFF_PBUF_SHIFT;
    public static final long IORING_OFF_MMAP_MASK;
    public static final int IORING_SQ_NEED_WAKEUP;
    public static final int IORING_SQ_CQ_OVERFLOW;
    public static final int IORING_SQ_TASKRUN;
    public static final int IORING_CQ_EVENTFD_DISABLED;
    public static final int IORING_ENTER_GETEVENTS;
    public static final int IORING_ENTER_SQ_WAKEUP;
    public static final int IORING_ENTER_SQ_WAIT;
    public static final int IORING_ENTER_EXT_ARG;
    public static final int IORING_ENTER_REGISTERED_RING;
    public static final int IORING_FEAT_SINGLE_MMAP;
    public static final int IORING_FEAT_NODROP;
    public static final int IORING_FEAT_SUBMIT_STABLE;
    public static final int IORING_FEAT_RW_CUR_POS;
    public static final int IORING_FEAT_CUR_PERSONALITY;
    public static final int IORING_FEAT_FAST_POLL;
    public static final int IORING_FEAT_POLL_32BITS;
    public static final int IORING_FEAT_SQPOLL_NONFIXED;
    public static final int IORING_FEAT_EXT_ARG;
    public static final int IORING_FEAT_NATIVE_WORKERS;
    public static final int IORING_FEAT_RSRC_TAGS;
    public static final int IORING_FEAT_CQE_SKIP;
    public static final int IORING_FEAT_LINKED_FILE;
    public static final int IORING_FEAT_REG_REG_RING;
    public static final int IORING_REGISTER_BUFFERS;
    public static final int IORING_UNREGISTER_BUFFERS;
    public static final int IORING_REGISTER_FILES;
    public static final int IORING_UNREGISTER_FILES;
    public static final int IORING_REGISTER_EVENTFD;
    public static final int IORING_UNREGISTER_EVENTFD;
    public static final int IORING_REGISTER_FILES_UPDATE;
    public static final int IORING_REGISTER_EVENTFD_ASYNC;
    public static final int IORING_REGISTER_PROBE;
    public static final int IORING_REGISTER_PERSONALITY;
    public static final int IORING_UNREGISTER_PERSONALITY;
    public static final int IORING_REGISTER_RESTRICTIONS;
    public static final int IORING_REGISTER_ENABLE_RINGS;
    public static final int IORING_REGISTER_FILES2;
    public static final int IORING_REGISTER_FILES_UPDATE2;
    public static final int IORING_REGISTER_BUFFERS2;
    public static final int IORING_REGISTER_BUFFERS_UPDATE;
    public static final int IORING_REGISTER_IOWQ_AFF;
    public static final int IORING_UNREGISTER_IOWQ_AFF;
    public static final int IORING_REGISTER_IOWQ_MAX_WORKERS;
    public static final int IORING_REGISTER_RING_FDS;
    public static final int IORING_UNREGISTER_RING_FDS;
    public static final int IORING_REGISTER_PBUF_RING;
    public static final int IORING_UNREGISTER_PBUF_RING;
    public static final int IORING_REGISTER_SYNC_CANCEL;
    public static final int IORING_REGISTER_FILE_ALLOC_RANGE;
    public static final int IORING_REGISTER_LAST;
    public static final int IORING_REGISTER_USE_REGISTERED_RING;
    public static final int IORING_RSRC_REGISTER_SPARSE;
    public static final int IO_WQ_BOUND;
    public static final int IO_WQ_UNBOUND;
    public static final int IORING_REGISTER_FILES_SKIP;
    public static final int IO_URING_OP_SUPPORTED;
    public static final int IOU_PBUF_RING_MMAP;
    public static final int IORING_RESTRICTION_REGISTER_OP;
    public static final int IORING_RESTRICTION_SQE_OP;
    public static final int IORING_RESTRICTION_SQE_FLAGS_ALLOWED;
    public static final int IORING_RESTRICTION_SQE_FLAGS_REQUIRED;
    public static final int IORING_RESTRICTION_LAST;

    protected LibIOURing() {
        throw new UnsupportedOperationException();
    }

    public static native int nio_uring_setup(int var0, long var1);

    public static int io_uring_setup(@NativeType(value="unsigned") int param0, @NativeType(value="struct io_uring_params *") IOURingParams param1) {
        return LibIOURing.nio_uring_setup(param0, param1.address());
    }

    public static native int nio_uring_register(int var0, int var1, long var2, int var4);

    public static int io_uring_register(int param0, @NativeType(value="unsigned") int param1, @NativeType(value="void *") long param2, @NativeType(value="unsigned") int param4) {
        return LibIOURing.nio_uring_register(param0, param1, param2, param4);
    }

    public static native int nio_uring_enter2(int var0, int var1, int var2, int var3, long var4, int var6);

    public static int io_uring_enter2(int param0, @NativeType(value="unsigned") int param1, @NativeType(value="unsigned") int param2, @NativeType(value="unsigned") int param3, @NativeType(value="sigset_t *") long param4, int param6) {
        return LibIOURing.nio_uring_enter2(param0, param1, param2, param3, param4, param6);
    }

    public static native int nio_uring_enter(int var0, int var1, int var2, int var3, long var4);

    public static int io_uring_enter(int param0, @NativeType(value="unsigned") int param1, @NativeType(value="unsigned") int param2, @NativeType(value="unsigned") int param3, @NativeType(value="sigset_t *") long param4) {
        return LibIOURing.nio_uring_enter(param0, param1, param2, param3, param4);
    }

    static {
        IORING_RESTRICTION_LAST = 4;
        IORING_RESTRICTION_SQE_FLAGS_REQUIRED = 3;
        IORING_RESTRICTION_SQE_FLAGS_ALLOWED = 2;
        IORING_RESTRICTION_SQE_OP = 1;
        IORING_RESTRICTION_REGISTER_OP = 0;
        IOU_PBUF_RING_MMAP = 1;
        IO_URING_OP_SUPPORTED = 1;
        IORING_REGISTER_FILES_SKIP = -2;
        IO_WQ_UNBOUND = 1;
        IO_WQ_BOUND = 0;
        IORING_RSRC_REGISTER_SPARSE = 1;
        IORING_REGISTER_USE_REGISTERED_RING = Integer.MIN_VALUE;
        IORING_REGISTER_LAST = 26;
        IORING_REGISTER_FILE_ALLOC_RANGE = 25;
        IORING_REGISTER_SYNC_CANCEL = 24;
        IORING_UNREGISTER_PBUF_RING = 23;
        IORING_REGISTER_PBUF_RING = 22;
        IORING_UNREGISTER_RING_FDS = 21;
        IORING_REGISTER_RING_FDS = 20;
        IORING_REGISTER_IOWQ_MAX_WORKERS = 19;
        IORING_UNREGISTER_IOWQ_AFF = 18;
        IORING_REGISTER_IOWQ_AFF = 17;
        IORING_REGISTER_BUFFERS_UPDATE = 16;
        IORING_REGISTER_BUFFERS2 = 15;
        IORING_REGISTER_FILES_UPDATE2 = 14;
        IORING_REGISTER_FILES2 = 13;
        IORING_REGISTER_ENABLE_RINGS = 12;
        IORING_REGISTER_RESTRICTIONS = 11;
        IORING_UNREGISTER_PERSONALITY = 10;
        IORING_REGISTER_PERSONALITY = 9;
        IORING_REGISTER_PROBE = 8;
        IORING_REGISTER_EVENTFD_ASYNC = 7;
        IORING_REGISTER_FILES_UPDATE = 6;
        IORING_UNREGISTER_EVENTFD = 5;
        IORING_REGISTER_EVENTFD = 4;
        IORING_UNREGISTER_FILES = 3;
        IORING_REGISTER_FILES = 2;
        IORING_UNREGISTER_BUFFERS = 1;
        IORING_REGISTER_BUFFERS = 0;
        IORING_FEAT_REG_REG_RING = 8192;
        IORING_FEAT_LINKED_FILE = 4096;
        IORING_FEAT_CQE_SKIP = 2048;
        IORING_FEAT_RSRC_TAGS = 1024;
        IORING_FEAT_NATIVE_WORKERS = 512;
        IORING_FEAT_EXT_ARG = 256;
        IORING_FEAT_SQPOLL_NONFIXED = 128;
        IORING_FEAT_POLL_32BITS = 64;
        IORING_FEAT_FAST_POLL = 32;
        IORING_FEAT_CUR_PERSONALITY = 16;
        IORING_FEAT_RW_CUR_POS = 8;
        IORING_FEAT_SUBMIT_STABLE = 4;
        IORING_FEAT_NODROP = 2;
        IORING_FEAT_SINGLE_MMAP = 1;
        IORING_ENTER_REGISTERED_RING = 16;
        IORING_ENTER_EXT_ARG = 8;
        IORING_ENTER_SQ_WAIT = 4;
        IORING_ENTER_SQ_WAKEUP = 2;
        IORING_ENTER_GETEVENTS = 1;
        IORING_CQ_EVENTFD_DISABLED = 1;
        IORING_SQ_TASKRUN = 4;
        IORING_SQ_CQ_OVERFLOW = 2;
        IORING_SQ_NEED_WAKEUP = 1;
        IORING_OFF_MMAP_MASK = 0xF8000000L;
        IORING_OFF_PBUF_SHIFT = 16L;
        IORING_OFF_PBUF_RING = 0x80000000L;
        IORING_OFF_SQES = 0x10000000L;
        IORING_OFF_CQ_RING = 0x8000000L;
        IORING_OFF_SQ_RING = 0L;
        IORING_CQE_BUFFER_SHIFT = 16;
        IORING_CQE_F_NOTIF = 8;
        IORING_CQE_F_SOCK_NONEMPTY = 4;
        IORING_CQE_F_MORE = 2;
        IORING_CQE_F_BUFFER = 1;
        IORING_MSG_RING_FLAGS_PASS = 2;
        IORING_MSG_RING_CQE_SKIP = 1;
        IORING_MSG_SEND_FD = 1;
        IORING_MSG_DATA = 0;
        IORING_ACCEPT_MULTISHOT = 1;
        IORING_NOTIF_USAGE_ZC_COPIED = Integer.MIN_VALUE;
        IORING_SEND_ZC_REPORT_USAGE = 8;
        IORING_RECVSEND_FIXED_BUF = 4;
        IORING_RECV_MULTISHOT = 2;
        IORING_RECVSEND_POLL_FIRST = 1;
        IORING_ASYNC_CANCEL_FD_FIXED = 8;
        IORING_ASYNC_CANCEL_ANY = 4;
        IORING_ASYNC_CANCEL_FD = 2;
        IORING_ASYNC_CANCEL_ALL = 1;
        IORING_POLL_ADD_LEVEL = 8;
        IORING_POLL_UPDATE_USER_DATA = 4;
        IORING_POLL_UPDATE_EVENTS = 2;
        IORING_POLL_ADD_MULTI = 1;
        IORING_SPLICE_F_FD_IN_FIXED = Integer.MIN_VALUE;
        IORING_TIMEOUT_UPDATE_MASK = 18;
        IORING_TIMEOUT_CLOCK_MASK = 12;
        IORING_TIMEOUT_MULTISHOT = 64;
        IORING_TIMEOUT_ETIME_SUCCESS = 32;
        IORING_LINK_TIMEOUT_UPDATE = 16;
        IORING_TIMEOUT_REALTIME = 8;
        IORING_TIMEOUT_BOOTTIME = 4;
        IORING_TIMEOUT_UPDATE = 2;
        IORING_TIMEOUT_ABS = 1;
        IORING_FSYNC_DATASYNC = 1;
        IORING_URING_CMD_FIXED = 1;
        IORING_OP_LAST = (byte)49;
        IORING_OP_SENDMSG_ZC = (byte)48;
        IORING_OP_SEND_ZC = (byte)47;
        IORING_OP_URING_CMD = (byte)46;
        IORING_OP_SOCKET = (byte)45;
        IORING_OP_GETXATTR = (byte)44;
        IORING_OP_FGETXATTR = (byte)43;
        IORING_OP_SETXATTR = (byte)42;
        IORING_OP_FSETXATTR = (byte)41;
        IORING_OP_MSG_RING = (byte)40;
        IORING_OP_LINKAT = (byte)39;
        IORING_OP_SYMLINKAT = (byte)38;
        IORING_OP_MKDIRAT = (byte)37;
        IORING_OP_UNLINKAT = (byte)36;
        IORING_OP_RENAMEAT = (byte)35;
        IORING_OP_SHUTDOWN = (byte)34;
        IORING_OP_TEE = (byte)33;
        IORING_OP_REMOVE_BUFFERS = (byte)32;
        IORING_OP_PROVIDE_BUFFERS = (byte)31;
        IORING_OP_SPLICE = (byte)30;
        IORING_OP_EPOLL_CTL = (byte)29;
        IORING_OP_OPENAT2 = (byte)28;
        IORING_OP_RECV = (byte)27;
        IORING_OP_SEND = (byte)26;
        IORING_OP_MADVISE = (byte)25;
        IORING_OP_FADVISE = (byte)24;
        IORING_OP_WRITE = (byte)23;
        IORING_OP_READ = (byte)22;
        IORING_OP_STATX = (byte)21;
        IORING_OP_FILES_UPDATE = (byte)20;
        IORING_OP_CLOSE = (byte)19;
        IORING_OP_OPENAT = (byte)18;
        IORING_OP_FALLOCATE = (byte)17;
        IORING_OP_CONNECT = (byte)16;
        IORING_OP_LINK_TIMEOUT = (byte)15;
        IORING_OP_ASYNC_CANCEL = (byte)14;
        IORING_OP_ACCEPT = (byte)13;
        IORING_OP_TIMEOUT_REMOVE = (byte)12;
        IORING_OP_TIMEOUT = (byte)11;
        IORING_OP_RECVMSG = (byte)10;
        IORING_OP_SENDMSG = (byte)9;
        IORING_OP_SYNC_FILE_RANGE = (byte)8;
        IORING_OP_POLL_REMOVE = (byte)7;
        IORING_OP_POLL_ADD = (byte)6;
        IORING_OP_WRITE_FIXED = (byte)5;
        IORING_OP_READ_FIXED = (byte)4;
        IORING_OP_FSYNC = (byte)3;
        IORING_OP_WRITEV = (byte)2;
        IORING_OP_READV = 1;
        IORING_OP_NOP = 0;
        IORING_SETUP_DEFER_TASKRUN = 8192;
        IORING_SETUP_SINGLE_ISSUER = 4096;
        IORING_SETUP_CQE32 = 2048;
        IORING_SETUP_SQE128 = 1024;
        IORING_SETUP_TASKRUN_FLAG = 512;
        IORING_SETUP_COOP_TASKRUN = 256;
        IORING_SETUP_SUBMIT_ALL = 128;
        IORING_SETUP_R_DISABLED = 64;
        IORING_SETUP_ATTACH_WQ = 32;
        IORING_SETUP_CLAMP = 16;
        IORING_SETUP_CQSIZE = 8;
        IORING_SETUP_SQ_AFF = 4;
        IORING_SETUP_SQPOLL = 2;
        IORING_SETUP_IOPOLL = 1;
        IOSQE_CQE_SKIP_SUCCESS = 64;
        IOSQE_BUFFER_SELECT = 32;
        IOSQE_ASYNC = 16;
        IOSQE_IO_HARDLINK = 8;
        IOSQE_IO_LINK = 4;
        IOSQE_IO_DRAIN = 2;
        IOSQE_FIXED_FILE = 1;
        IOSQE_CQE_SKIP_SUCCESS_BIT = 6;
        IOSQE_BUFFER_SELECT_BIT = 5;
        IOSQE_ASYNC_BIT = 4;
        IOSQE_IO_HARDLINK_BIT = 3;
        IOSQE_IO_LINK_BIT = 2;
        IOSQE_IO_DRAIN_BIT = 1;
        IOSQE_FIXED_FILE_BIT = 0;
        IORING_MAX_ENTRIES = 4096;
        IORING_FILE_INDEX_ALLOC = -1;
        Library.initialize();
    }
}

